language: objective-c
install:
  - npm install
before_script:
  - chmod +x ./ios/RockCer/add-key.sh
  - cd ./ios/RockCer
  - ./add-key.sh
  - cd -
script:
  - xcodebuild -project "./ios/FunkRock.xcodeproj" -scheme "FunkRock_Test" archive -archivePath "./buildIOSTemp/FunkRock_Test.xcarchive" -quiet
  - xcodebuild -exportArchive -archivePath "./buildIOSTemp/FunkRock_Test.xcarchive" -exportPath "./buildIOSTemp/FunkRock_Test" -exportOptionsPlist "exportTestOptions.plist" -quiet
  - cd ./buildIOSTemp && ls -R
  # - curl